### ISSUE TITLE
Installation on filament 3

### ISSUE THREAD

**Issue by l-mtc** [ArtMin96/filament-jet#10]
Problem 1
    - artmin96/filament-jet[0.0.1, ..., 0.0.2] require filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.55] but it conflicts with your root composer.json require (^3.0-stable).
    - Root composer.json requires artmin96/filament-jet * -> satisfiable by artmin96/filament-jet[0.0.1, 0.0.2].

**Comment by ArtMin96** [comment]
Hi @l-mtc. The package does not support Filament v3
