### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by flashmediasolutions** [ArtMin96/filament-jet#7]
Is there any plan to support Laravel 10?

**Comment by ArtMin96** [comment]
Yes. Also, some new things should be added. But maybe next week.

**Comment by humayunghani** [comment]
Still Laravel 10 not supported? Are you still going to support this project or has this been abandon already?

**Comment by ArtMin96** [comment]
I don't have time to update right now.

**Comment by ArtMin96** [comment]
Added
